//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dealership2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryD
    {
        public int InventoryDID { get; set; }
        public string Title { get; set; }
        public Nullable<int> AdminID { get; set; }
    
        public virtual SystemAdmin SystemAdmin { get; set; }
    }
}
